# Étape 1 : Construction du frontend
FROM node:18 AS builder
WORKDIR /frontend
COPY package.json package-lock.json ./
RUN npm install
COPY . .

# Ne pas exécuter "npm run build", juste démarrer le serveur de développement.
CMD ["npm", "run", "dev"]
