version: "3.8"

services:
  # Service pour l'API Next.js
  api:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "3000:3000"  # Expose le port 3000
    volumes:
      - .:/app  # Monte le code source dans le conteneur
    environment:
      NODE_ENV: production
    command: sh -c "npm run build && npm start"
    depends_on:
      - db  # Dépendance à la base de données

  # Service pour la base de données PostgreSQL
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: strongman
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Service pour pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@armstrong.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    depends_on:
      - db 

volumes:
  postgres_data:
